-- World Builder data. This file is entirely maintained by the World Builder.
-- Tile legend: . grass, = path, ~ water, H house, T tree, # forest,
-- W wooden wall, K timber roof, D door, F wooden floor, C counter, B bonfire,
-- A feast table, S dueling sand, M marble, Q marble roof, E workshop tools,
-- R rail, X walkable rail crossing, G metal grate, I industrial brick,
-- P machinery, V furnace, J industrial roof, U timber bridge, O rocky cliff.
return {
	maps = {
		{
			id = "emberglen",
			name = "Emberglen",
			indoor = false,
			tiles = {
				"####################################",
				"#TTT..........QQQQQQQ..........TTTT#",
				"#TTT..........QQQQQQQ..........TTTT#",
				"#.KKKKKKK.....MMMMMMM.~~~~~TT..TTTT#",
				"#.KKKKKKK..TT.MMMDMMM.~~~~~T.......#",
				"#.WWWWWWW........=....~~~~~......T.#",
				"#.WWWDWWWTT......=.....~~~.........#",
				"#..TT===T=========..........KKKKKK.#",
				"#....=...........=..........KKKKKK.#",
				"#.SSSSSSSSS.===========.....WWWWKK.#",
				"#.SSSSSSSSS.==A=====A==.....WWDWWW.#",
				"#.SSSSSSSSS.===================.WW.#",
				"#.SSSSSSSS=======B==================",
				"#.SSSSSSSSS.===========............#",
				"#.SSSSSSSSS.==A=====A=============.#",
				"#.SSSSSSSSS.===========............#",
				"#.SSSSSSSSS......=...............TT#",
				"#........TT......=.................#",
				"#................=....TTT..........#",
				"#................=.......KKKKKKK####",
				"#########........=.......KKKKKKK####",
				"#########........=.......KKKKKKW####",
				"#########...TT...=.......WWWDWW.####",
				"#########........============...####",
				"#########.......................####",
				"####################################"
			}
		},
		{
			id = "old_road",
			name = "The Old Road",
			indoor = false,
			tiles = {
				"##############################OOOOOOOOOOOOOOOOOO",
				"######............~............................O",
				"######.####.......~.........OOO......OOOOOOO...O",
				"######.####....T..~~........OOO......OOOOOOO...O",
				"######.####......~~......T...........OOOOOOO...O",
				"######............~~............OOOOO..........O",
				"#......T....T.....~~............OOOOO..........O",
				"#.............B....~.....M......OOOOO..........O",
				"#...T.............~~.....................OOOOOOO",
				"#.......==========UUUU========...........OOOOOOO",
				"#.......==========UUUU=========..........OOOOOOO",
				"#.......==.........~~........==....M...........O",
				"==========...MT.....~........==................O",
				"#=========...=......~~.......===================",
				"#.......=....=......~........==================O",
				"#.T.....=.KKKKKKK...~..........................O",
				"#.......=.KKKKKKK..~~..........................O",
				"#.......=.WWWWWWW...~~............OOOOOO.......O",
				"#######.=.WWWDWWW...~~.......T....OOOOOO..OOOOOO",
				"#######.======##.....~............OOOOOO..OOOOOO",
				"#######....#=###.....~~...........OOOOOO..OOOOOO",
				"#######....#####.....~....................OOOOOO",
				"#######....#####.....~....................OOOOOO",
				"##############################OOOOOOOOOOOOOOOOOO"
			}
		},
		{
			id = "cinderrail",
			name = "Cinderrail Foundry",
			indoor = false,
			tiles = {
				"####################################################",
				"#.....................JJJJJJ............JJJJJJJJJJ.#",
				"#..JJJJJJJJJJJ..P.....JJJJJJ...P.....P..JJJJJJJJJJ.#",
				"#..JJJJJJJJJJJ....P...IIIIII......P.....IJJJJJJJJI.#",
				"#..IIIIIIIIIII........III==I............IIIIIIIIII.#",
				"#..IIIII==IIII..GG.......==..............III==III..#",
				"#.......==......GG.......==.................==.....#",
				"#RRRRRRRXXRRRRRRRRRRRRRRRXXRRRRRRRRRRRRRRRRRXXRRRRR#",
				"#RRRRRRRXXRRRRRRRRRRRRRRRXXRRRRRRRRRRRRRRRRRXXRRRRR#",
				"#.......==...............==.................==.....#",
				"#.================================================.#",
				"#.================================================.#",
				"#..JJJJJJJ..JJJJJJJ.GGGGGGGGGGG.JJJJJJ..JJJJJJJJJJJ#",
				"#..JJJJJJJ..JJJJJJJ.GGGGGGGGGGG.JJJJJJ..JJJJJJJJJJJ#",
				"#..IIIIIII..IIIIIII.GGGGSSSGGGG.IIIIII..IIIIIIIIIII#",
				"#..III=III..III=III.GGGSGGGSGGG.II=III..IIIII=IIIII#",
				"====================GGGSGPGSGGG=====================",
				"====================GGGSGGGSGGG=====================",
				"#.JJJJ.JJJJ....==...GGGGSSSGGGG...==.........==....#",
				"#.JJJJ.JJJJ....==...GGGGGGGGGGG...==.........==....#",
				"#.IDII.IDII....==...GGGGGG=========================#",
				"#..............==...GGGGGG=========================#",
				"#.JJJJ.JJJJ....==...GGGGGGGGGGG.GG...........==....#",
				"#.JJJJ.JJJJ.JJJJJJJJJ....==.....GG......IIIII==IIII#",
				"#.IDII.IDII.JJJJJJJJJ....==.GGGGGGGGGG..ISSSSSSSSSI#",
				"============JJJJJJJJJ======.GGGGGGGGGG..ISSSSSSSSSI#",
				"============JJJJJJJJJ======.VV..GG..VV..ISSSSSSSSSI#",
				"#...........IIIIIIIII.JJJJJPVVP.GG.PVVP.ISSSSSSSSSI#",
				"#..JJJJJJJ..IIII=IIII.JJJJJ.....VV......ISSSSSSSSSI#",
				"#..JJJJJJJ......==....JJJJJ.....VV......ISSSSSSSSSI#",
				"#..IIIIIII......==....IIDII..P..GG..P...ISSSSSSSSSI#",
				"#..IIIDIII......==.......==.....GG......ISSSSSSSSSI#",
				"#...............==.......==.JJJJDDJJJJ..IIIII==IIII#",
				"#...............============IIVIIIIVII.......==....#",
				"#...............=================IIIII.......==....#",
				"#########################==#########################"
			}
		},
		{
			id = "mercers_house",
			name = "Mercer's House",
			indoor = true,
			tiles = {
				"WWWWWWWWWW",
				"WEEFFFFFEW",
				"WFFFFFFFFW",
				"WFFCCCCFFW",
				"WFFFFFFFFW",
				"WFFFFFFFFW",
				"WFFFFFFFFW",
				"WWWWWDWWWW"
			}
		},
		{
			id = "rook_mira_home",
			name = "Rook and Mira's Home",
			indoor = true,
			tiles = {
				"WWWWWWWWWW",
				"WFFFFFFFFW",
				"WFFFFFFFFW",
				"WFFAAFFFFW",
				"WFFFFFFFFW",
				"WFFFFFFFFW",
				"WFFFFFFFFW",
				"WWWWWDWWWW"
			}
		}
	},
	start = { map = "emberglen", x = 17, y = 15 },
	portals = {
		{ from = { map = "emberglen", x = 30, y = 10 },
			to = { map = "mercers_house", x = 5, y = 6 } },
		{ from = { map = "mercers_house", x = 5, y = 7 },
			to = { map = "emberglen", x = 30, y = 11 } },
		{ from = { map = "emberglen", x = 5, y = 6 },
			to = { map = "rook_mira_home", x = 5, y = 6 } },
		{ from = { map = "rook_mira_home", x = 5, y = 7 },
			to = { map = "emberglen", x = 5, y = 7 } },
		{ from = { map = "emberglen", x = 35, y = 12 },
			to = { map = "old_road", x = 2, y = 12 } },
		{ from = { map = "old_road", x = 0, y = 12 },
			to = { map = "emberglen", x = 34, y = 12 } },
		{ from = { map = "old_road", x = 47, y = 13 },
			to = { map = "cinderrail", x = 2, y = 16 } },
		{ from = { map = "cinderrail", x = 0, y = 16 },
			to = { map = "old_road", x = 45, y = 13 } }
	},
	npcs = {
		["mira"] = { map = "rook_mira_home", x = 5, y = 2 },
		["marin"] = { map = "emberglen", x = 4, y = 12 },
		["rook"] = { map = "old_road", x = 24, y = 9 },
		["aurelia"] = { map = "emberglen", x = 17, y = 5 },
		["flint"] = { map = "emberglen", x = 5, y = 10 },
		["nyx"] = { map = "emberglen", x = 28, y = 23 },
		["tidal"] = { map = "emberglen", x = 6, y = 15 },
		["briar"] = { map = "emberglen", x = 8, y = 12 },
		["mercer"] = { map = "mercers_house", x = 5, y = 2 },
		["veiled_one"] = { map = "emberglen", x = 17, y = 10 },
		["pip"] = { map = "emberglen", x = 12, y = 8 },
		["noma"] = { map = "emberglen", x = 22, y = 11 },
		["bram"] = { map = "emberglen", x = 14, y = 23 },
		["elia"] = { map = "emberglen", x = 3, y = 17 },
		["tomas"] = { map = "emberglen", x = 21, y = 23 },
		["senn"] = { map = "emberglen", x = 29, y = 18 },
		["kipp"] = { map = "cinderrail", x = 11, y = 25 },
		["ansa"] = { map = "cinderrail", x = 47, y = 20 },
		["holt"] = { map = "cinderrail", x = 34, y = 25 },
	},
	shards = {
		["living_dead"] = { map = "emberglen", x = 4, y = 1 },
		["ghost"] = { map = "emberglen", x = 30, y = 23 },
		["chimera"] = { map = "emberglen", x = 11, y = 2 },
		["parasite_worm"] = { map = "emberglen", x = 25, y = 2 },
		["human"] = { map = "emberglen", x = 10, y = 5 },
		["armoroid"] = { map = "emberglen", x = 12, y = 7 },
		["rock_beast"] = { map = "emberglen", x = 23, y = 7 },
		["machine_eater"] = { map = "emberglen", x = 34, y = 6 },
		["dragonoid"] = { map = "emberglen", x = 24, y = 10 },
		["fire"] = { map = "emberglen", x = 34, y = 9 },
		["giant_insect"] = { map = "emberglen", x = 1, y = 18 },
		["colony_beetle"] = { map = "emberglen", x = 6, y = 18 },
		["horned_beast"] = { map = "emberglen", x = 12, y = 19 },
		["beast_folk"] = { map = "emberglen", x = 20, y = 18 },
		["tree_folk"] = { map = "emberglen", x = 34, y = 18 },
		["fish"] = { map = "emberglen", x = 27, y = 6 },
		["cyber_lord"] = { map = "emberglen", x = 26, y = 12 },
		["cyber_virus"] = { map = "emberglen", x = 32, y = 12 },
		["liquid_people"] = { map = "emberglen", x = 13, y = 16 },
	}
}
